spring:
  application:
    name: product-mgmt-service

server:
  port: 8443

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    hostname: localhost